---
name: Backlog Limits Checker
# yamllint disable-line rule:truthy
on:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  check_suse_qa_tools_backlog_limits:
    # prevent running this on forks or any other branches
    if: github.ref == 'refs/heads/master' && github.repository_owner == 'os-autoinst'
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install markdown
      - name: prepare output md file
        run: |
          rm -f index.md
          python backlog_checker.py
      - name: check overall backlog length
        if: always()
        run: |
          python backlog_checker.py
        env:
          key: ${{ secrets.REDMINE_API_KEY }}
          fun: "gha_overall"
      - name: check workable backlog length
        if: always()
        run: |
          python backlog_checker.py
        env:
          key: ${{ secrets.REDMINE_API_KEY }}
          fun: "gha_workable"
      - name: check issues exceeding due date
        if: always()
        run: |
          python backlog_checker.py
        env:
          key: ${{ secrets.REDMINE_API_KEY }}
          fun: "gha_exceed_due_date"
      - name: check untriaged 'tools' tagged issues
        if: always()
        run: |
          python backlog_checker.py
        env:
          key: ${{ secrets.REDMINE_API_KEY }}
          fun: "gha_untriaged_tools"
      - name: check untriaged issues
        if: always()
        run: |
          python backlog_checker.py
        env:
          key: ${{ secrets.REDMINE_API_KEY }}
          fun: "gha_untriaged_qa"
      - name: Commit files
        if: always()
        run: |
          mkdir -p gh-pages
          python -m markdown index.md > gh-pages/index.html
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add gh-pages/
          git commit --no-edit -m "Update index.html" -a
      - name: Push changes
        if: always()
        uses: JamesIves/github-pages-deploy-action@4.1.6
        with:
          branch: gh-pages
          folder: gh-pages
