---
name: Unit Tests
# yamllint disable-line rule:truthy
on: [push, pull_request]
jobs:
  schedule:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.8
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - run: pytest -vv
      - name: Install Telegraf
        run: sudo apt-get install -y telegraf
      - name: Test InfluxDB output
        run: telegraf --test --config tests/slo.conf
